version: '3'

networks:
  account-service:
    external: true
  microservices:
    external: true


services:

  account-service-api:
    image: assignment123/account-service
    build:
      context: ../../..
      dockerfile: _config/docker/image/Dockerfile

    container_name: account-service-api
    hostname: account-service-api
#    command: "/scripts/run-java.sh"
#    volumes:
#      -
    ports:
      - 8081:8080

    networks:
      - account-service
      - microservices

    env_file:
      - "../env/development.env"
