version: '3'

networks:
  microservices:
    external: true

services:

  account-service-db:
    image: mariadb:latest
    container_name: account-service-db
    hostname: account-service-db

    networks:
      - microservices

#    ports:
#      - 3307:3306

    volumes:
      - "../volumes/mysql:/var/lib/mysql"

    env_file:
      - "../env/development.env"


